### ISSUE TITLE
Feature request: Default animations as part of the theme

### ISSUE THREAD

**Issue by Mhoog** [Atom-Learning/components#151]
## Component Name(\*) or Feature Name
Animations

## Description(\*)
It would be nice to have a set of default animations (in the form of Utils?) that we can easily add to nodes:
1. A set of default `transitions`, so that we have the same Bezier curves and durations for our animations throughout the application when we want to transition CSS properties.
2. A set of default `animation keyframes` that we can use as entry effects or after user interaction. For example, a set of predefined animations like [Reboundgen](http://dwarcher.github.io/reboundgen/examples/) or [Animate CSS](https://animate.style/) has.

Hopefully having the animations easily available will also increase the usage of animations in our application :)

**Comment by thomasdigby** [comment]
@Mhoog Yep totally agree, I think the reason we haven't done that already is because it's not baked into the system-ui tokens (although I've just seen that `transitions` are 🤦 https://github.com/modulz/stitches/blob/bcd76ccaf48341eb225b50ef468e28ccbe6ed39d/packages/core/src/defaultThemeMap.js).

I guess we just need to define what we should export, `keyframes`, `transitions`, transition durations, or a mix of everything, like our components. e.g. export the underlying values as well as some combined animations that you can drop in.

**Comment by MiguelGDLR** [comment]
@andoulla This ticket seems very similar to the one I just mentioned so I put them together here [](https://atomlearningltd.atlassian.net/browse/DS-89)

We can remove this Issue
