### ISSUE TITLE
Button: Loading state gets rendered in snapshots even when not visible

### ISSUE THREAD

**Issue by andoulla** [Atom-Learning/components#241]
## Component Name (\*)
Button

## Expected Behaviour (\*)
When `isLoading=false`, the loader shouldn't appear in snapshots 

## Actual Behaviour (\*)
Occasionally the loader shows up in the parent component's snapshot

Examples:
```
<div
          class="c-dhzjXW c-dhzjXW-ibICGYT-css"
          role="alert"
        >
          <span
            style="position: absolute; border: 0px; width: 1px; height: 1px; padding: 0px; margin: -1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; word-wrap: normal;"
          >
            Loading
          </span>
          <div
            class="c-jBOHFZ c-jBOHFZ-jIYkAt-size-md"
          />
          <div
            class="c-jBOHFZ c-jBOHFZ-jIYkAt-size-md"
          />
          <div
            class="c-jBOHFZ c-jBOHFZ-jIYkAt-size-md"
          />
        </div>
      </div>
```

## Other information (\*)

This is coming up only in the parent (caller) component

**Comment by alexandrunemes** [comment]
The only way to avoid this is to initialize the `isLoading` value to some falsy value other than `false`. Maybe `null`. Then the button would only render its children. When you pass it `isLoading={false}`, it wraps its children with  an HOC that renders the `<Loader/>` component alongside the children, with the visibility set to `0`. So even if not visible, the DOM elements that represents the loader are still part of the DOM and they become part of the snapshot.

Note that due to the CSS involved, if you start off with `isLoading={null}`, the first transition to `isLoading={true}` will be sudden, while any subsequent ones (true->false, false->true) will have a 150ms animation time.
